import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { fileURLToPath } from "node:url";
import path from "node:path";

import {
  buildPaidLanding,
  PAID_CHECKOUT_PATH,
  PAID_LANDING_ENTRY_TOKEN_PLACEHOLDER
} from "../scripts/build-paid-landing.mjs";

const testPath = fileURLToPath(import.meta.url);
const repositoryRoot = path.resolve(path.dirname(testPath), "..");
const canonicalPath = path.join(repositoryRoot, "index.html");
const publishedPaidLandingPath = path.join(
  repositoryRoot,
  "public",
  "mobile-paid-prototype.html"
);

const [canonicalHtml, paidLandingHtml] = await Promise.all([
  readFile(canonicalPath, "utf8"),
  readFile(publishedPaidLandingPath, "utf8")
]);

function renderedText(html) {
  return html
    .replace(/<script\b[\s\S]*?<\/script>/gi, " ")
    .replace(/<style\b[\s\S]*?<\/style>/gi, " ")
    .replace(/<!--[\s\S]*?-->/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

test("committed paid landing is the deterministic canonical render", () => {
  assert.equal(paidLandingHtml, buildPaidLanding(canonicalHtml));
  assert.match(
    paidLandingHtml,
    /Generated by scripts\/build-paid-landing\.mjs from index\.html/
  );
});

test("paid render is noindex and canonically isolated from the root page", () => {
  assert.match(
    paidLandingHtml,
    /<meta name="robots" content="noindex,nofollow" \/>/
  );
  assert.match(
    paidLandingHtml,
    /<link rel="canonical" href="https:\/\/sidestream\.tv\/" \/>/
  );
  assert.match(paidLandingHtml, /data-mobile-paid-variant-ready="true"/);

  assert.doesNotMatch(canonicalHtml, /data-mobile-paid-variant/);
  assert.doesNotMatch(canonicalHtml, /sidestream-paid-entry-token/);
  assert.doesNotMatch(canonicalHtml, /\/api\/paid-acquisition\/checkout/);
});

test("rendered paid page contains no prohibited free or pre-purchase email offer", () => {
  const text = renderedText(paidLandingHtml);
  const prohibited = [
    /\bStart free\b/i,
    /\bFree Download\b/i,
    /\b5 free downloads\b/i,
    /\$0\s*forever/i,
    /Email me the download link/i,
    /We'll email you a link to your computer/i,
    /20%\s*off/i,
    /STREAM20/i
  ];

  prohibited.forEach((pattern) => assert.doesNotMatch(text, pattern));
  assert.match(text, /Buy Now \$14\.99/);
  assert.match(text, /\$14\.99 once/);
  assert.match(text, /We’ll email your download link after purchase\./);
});

test("every paid CTA enters only the server-owned Checkout boundary", () => {
  assert.equal(
    paidLandingHtml.split(PAID_CHECKOUT_PATH).length - 1,
    1,
    "the paid Checkout endpoint should appear only in the explicit-submit script"
  );
  assert.match(paidLandingHtml, /method: "POST"/);
  assert.match(
    paidLandingHtml,
    /body: JSON\.stringify\(\{\s*schemaVersion: 1,\s*entryToken: paidEntryToken,\s*idempotencyKey\s*\}\)/
  );
  assert.doesNotMatch(paidLandingHtml, /\/api\/checkout\/start/);
  assert.doesNotMatch(paidLandingHtml, /\/upgrade\.html/);
  assert.doesNotMatch(paidLandingHtml, /https:\/\/sidestream\.tv\/api\/download/);
  assert.doesNotMatch(paidLandingHtml, /\/api\/send-download-links/);
  assert.doesNotMatch(paidLandingHtml, /window\.location\.search|URLSearchParams/);

  assert.equal(
    paidLandingHtml.split(PAID_LANDING_ENTRY_TOKEN_PLACEHOLDER).length - 1,
    1,
    "the router must have exactly one unambiguous placeholder to replace"
  );
});

test("rendering is immediate and never fetches the canonical page at runtime", () => {
  assert.doesNotMatch(paidLandingHtml, /fetch\s*\(\s*["']\/index\.html/);
  assert.doesNotMatch(paidLandingHtml, /DOMParser|document\.open|document\.write/);
  assert.match(paidLandingHtml, /<div id="shader-background-root"/);
  assert.match(paidLandingHtml, /<script type="module" src="\/src\/main\.tsx"><\/script>/);
  assert.match(paidLandingHtml, /const demoVideoPrewarmObserver/);
  assert.match(paidLandingHtml, /const loopingVideoPrewarmObserver/);
});

test("mobile source carries the accessibility and no-overflow contract", () => {
  assert.match(
    paidLandingHtml,
    /<meta name="viewport" content="width=device-width, initial-scale=1\.0" \/>/
  );
  assert.match(
    paidLandingHtml,
    /html\[data-mobile-paid-variant\] body \{\s*max-width: 100%;\s*overflow-x: clip;/
  );
  assert.match(paidLandingHtml, /min-height: 52px;/);
  assert.match(paidLandingHtml, /\.btn:focus-visible \{\s*outline: 3px solid #fff;/);
  assert.match(paidLandingHtml, /role="status" aria-live="polite"/);
  assert.match(
    paidLandingHtml,
    /aria-label="Buy Sidestream Pro now for \$14\.99, one-time purchase"/
  );
});
