import { execFileSync } from "node:child_process";
import { readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const pageSource = "index.html";
const templatePath = path.join(projectRoot, "public", "sitemap.xml");
const outputPath = path.join(projectRoot, "dist", "sitemap.xml");
const lastmodMarker =
  "    <!-- lastmod generated by scripts/generate-sitemap.mjs -->";

function readGit(args) {
  return execFileSync("git", args, {
    cwd: projectRoot,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();
}

async function getVercelGitHubLastModifiedAt() {
  const commitSha = process.env.VERCEL_GIT_COMMIT_SHA;

  if (!commitSha) {
    return null;
  }

  const provider = process.env.VERCEL_GIT_PROVIDER;

  if (provider && provider !== "github") {
    return null;
  }

  const owner = process.env.VERCEL_GIT_REPO_OWNER ?? "alexgmov";
  const repository =
    process.env.VERCEL_GIT_REPO_SLUG ?? "Sidestream-Website";
  const commitsUrl = new URL(
    `https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repository)}/commits`,
  );
  commitsUrl.search = new URLSearchParams({
    path: pageSource,
    sha: commitSha,
    per_page: "1",
  }).toString();

  const response = await fetch(commitsUrl, {
    headers: {
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    signal: AbortSignal.timeout(10_000),
  });

  if (!response.ok) {
    throw new Error(
      `GitHub could not resolve ${pageSource} history (${response.status})`,
    );
  }

  const commits = await response.json();
  const committedAt = commits?.[0]?.commit?.committer?.date;

  if (!committedAt) {
    throw new Error(
      `GitHub returned no committed date for ${pageSource} at ${commitSha}`,
    );
  }

  return new Date(committedAt);
}

async function getLastModifiedAt() {
  const vercelGitHubDate = await getVercelGitHubLastModifiedAt();

  if (vercelGitHubDate) {
    return vercelGitHubDate;
  }

  try {
    const isDirty = Boolean(
      readGit(["status", "--porcelain=v1", "--", pageSource]),
    );

    if (isDirty) {
      return (await stat(path.join(projectRoot, pageSource))).mtime;
    }

    const committedAt = readGit([
      "log",
      "-1",
      "--format=%cI",
      "--",
      pageSource,
    ]);

    if (committedAt) {
      return new Date(committedAt);
    }
  } catch {
    // Omit lastmod when local Git metadata cannot prove when the page changed.
  }

  return null;
}

const template = await readFile(templatePath, "utf8");

if (!template.includes(lastmodMarker)) {
  throw new Error(`Missing sitemap lastmod marker in ${templatePath}`);
}

const lastModifiedAt = await getLastModifiedAt();

if (lastModifiedAt && Number.isNaN(lastModifiedAt.getTime())) {
  throw new Error(`Could not determine a valid lastmod for ${pageSource}`);
}

const sitemap = template.replace(
  lastmodMarker,
  lastModifiedAt
    ? `    <lastmod>${lastModifiedAt.toISOString()}</lastmod>`
    : "",
);

await writeFile(outputPath, sitemap, "utf8");

if (lastModifiedAt) {
  console.log(
    `Generated dist/sitemap.xml with ${pageSource} lastmod ${lastModifiedAt.toISOString()}`,
  );
} else {
  console.log(
    `Generated dist/sitemap.xml without lastmod because ${pageSource} history is unavailable`,
  );
}
